name = "cityexperts-website"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables (for local development)
[vars]
ENVIRONMENT = "development"
CONTACT_EMAIL = "info@cityexperts.ae"
FROM_EMAIL = "noreply@cityexperts.ae"

# Environment-specific configurations
[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

# Development configuration (for Pages Functions)
[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"